export default function getPages() {
	return [
		{
			id: '123',
			label: 'First Page',
			elements: [
				{
					id: '35674',
					type: 'circle',
					selected: false,
					hover: false,
					x: 100,
					y: 100,
					color: 'red',
					radius: 60,
					start_angle: 0,
					end_angle: 2 * Math.PI,
				},
				{
					id: '3457',
					type: 'group',
					selected: false,
					hover: false,
					elements: [
						{
							type: 'ellipse',
							selected: false,
							hover: false,
							x: 100,
							y: 100,
							color: 'black',
							radius_x: 60,
							radius_y: 80,
							rotation: 0,
							start_angle: 0,
							end_angle: 2 * Math.PI,
						},
						{
							type: 'ellipse',
							selected: false,
							hover: false,
							x: 200,
							y: 200,
							color: 'black',
							radius_x: 60,
							radius_y: 80,
							rotation: 0,
							start_angle: 0,
							end_angle: 2 * Math.PI,
						},
					],
				},
				{
					id: '67484',
					type: 'ellipse',
					selected: false,
					hover: false,
					x: 1500,
					y: 1500,
					color: 'red',
					radius_x: 60,
					radius_y: 80,
					rotation: 0,
					start_angle: 0,
					end_angle: 2 * Math.PI,
				},
				{
					id: '4678',
					type: 'ellipse',
					selected: false,
					hover: false,
					x: 100,
					y: 1500,
					color: 'red',
					radius_x: 60,
					radius_y: 80,
					rotation: 0,
					start_angle: 0,
					end_angle: 2 * Math.PI,
				},
				{
					id: '3567',
					type: 'ellipse',
					selected: false,
					hover: false,
					x: 1500,
					y: 100,
					color: 'red',
					radius_x: 60,
					radius_y: 80,
					rotation: 0,
					start_angle: 0,
					end_angle: 2 * Math.PI,
				},
				{
					id: '8764',
					type: 'ellipse',
					selected: false,
					hover: false,
					x: 800,
					y: 800,
					color: 'red',
					radius_x: 60,
					radius_y: 80,
					rotation: 0,
					start_angle: 0,
					end_angle: 2 * Math.PI,
				},
			],
		},
	];
}
