const asjectives = [
	'Dead',
	'Hairless',
	'Sadistic',
	'Metal',
	'Wild',
	'Domesticated',
	'Abnormal',
	'Medicated',
	'Cocky',
	'Massive',
	'Disrespectful',
	'Impressive',
	'Out of control',
	'Internet worthy',
	'Hilarious',
	'Sexy',
	'Hot',
	'Very tactful',
	'Bearded',
	'Duck-like',
	'Violent',
	'Slimy',
	'Insanely creepy',
	'Embarrassed to the bone',
	'Self-centered',
	'Talking',
	'Naked',
	'Angry',
	'Shaky',
	'Deep',
	'Sick',
	'Zippy',
	'Sticky',
	'Fluffy',
	'Frozen',
	'Unholy',
	'Painfully honest',
	'Filthy',
	'Fighting',
	'Bonkers',
	'Harsh',
	'Frisky',
	'Greedy',
	'Crawly',
	'Insane',
	'Hideous',
	'Ungodly',
	'Abusive',
	'Drunken',
	'Hateful',
	'Idiotic',
	'Twisted',
	'Useless',
	'Yapping',
	'Magical',
	'Indecent',
	'Godawful',
	'Arrogant',
	'Confused',
	'Flirting',
	'High-end',
	'Insecure',
	'Maniacal',
	'Sickened',
	'Slippery',
	'Stubborn',
	'Tripping',
	'Vengeful',
	'Sinister',
	'Costumed',
	'Cowardly',
	'Haunting',
	'Startled',
	'Alcoholic',
	'Demanding',
	'Shivering',
	'Offensive',
	'Nighttime',
	'Startling',
	'Disgusting',
	'Slap happy',
	'Disturbing',
	'Adulterous',
	'Blathering',
	'Flickering',
	'Rebellious',
	'Impertinent',
	'Bull headed',
	'Hyperactive',
	'Infuriating',
	'Outnumbered',
	'Pea-brained',
	'Territorial',
	'Underhanded',
	'Zombie like',
	'Mischievous',
	'At-the-ready',
	'Free-loading',
	'House-broken',
	'Up-to-no-good',
	'Cruel-hearted',
	'Misunderstood',
	'Narrow-minded',
	'Self-absorbed',
	'Bat-shit-crazy',
	'Fiercely-loyal',
	'Out-of-control',
	'Fear-inspiring',
	'Bat shit crazy',
	'Mentally impaired',
];

export default asjectives[Math.floor(Math.random() * asjectives.length)];
