export default [
	'Arial',
	'Helvetica',
	'Verdana',
	'Calibri',
	'Noto',
	'Lucida Sans',
	'Gill Sans',
	'Century Gothic',
	'Candara',
	'Futara',
	'Franklin Gothic Medium',
	'Trebuchet MS',
	'Geneva',
	'Segoe UI',
	'Optima',
	'Avanta Garde',
	'Times New Roman',
	'Big Caslon',
	'Bodoni MT',
	'Book Antiqua',
	'Bookman',
	'New Century Schoolbook',
	'Calisto MT',
	'Cambria',
	'Didot',
	'Garamond',
	'Georgia',
	'Goudy Old Style',
	'Hoefler Text',
	'Lucida Bright',
	'Palatino',
	'Perpetua',
	'Rockwell',
	'Rockwell Extra Bold',
	'Baskerville',
	'Consolas',
	'Courier',
	'Courier New',
	'Lucida Console',
	'Lucidatypewriter',
	'Lucida Sans Typewriter',
	'Monaco',
	'Andale Mono',
	'CURSIVE FONT FAMILY',
	'Comic Sans',
	'Comic Sans MS',
	'Apple Chancery',
	'Zapf Chancery',
	'Bradley Hand',
	'Brush Script MT',
	'Brush Script Std',
	'Snell Roundhan',
	'URW Chancery',
	'Coronet script',
	'Florence',
	'Parkavenue',
	'Impact',
	'Brushstroke',
	'Luminari',
	'Chalkduster',
	'Jazz LET',
	'Blippo',
	'Stencil Std',
	'Marker Felt',
	'Trattatello',
	'Arnoldboecklin',
	'Oldtown',
	'Copperplate',
	'papyrus',
	'Abadi MT Condensed Light',
	'Aharoni',
	'Aharoni Bold',
	'Aldhabi',
	'AlternateGothic2 BT',
	'Andalus',
	'Angsana New',
	'AngsanaUPC',
	'Aparajita',
	'Arabic Typesetting',
	'Bahnschrift',
	'Bahnschrift Light',
	'Bahnschrift SemiBold',
	'Bahnschrift SemiLight',
	'Batang',
	'BatangChe',
	'BIZ UDGothic',
	'BIZ UDMincho Medium',
	'Browallia New',
	'BrowalliaUPC',
	'Calibri Light',
	'Cambodian',
	'Cambria Math',
	'Cherokee',
	'Constantia',
	'Copperplate Gothic Light',
	'Copperplate Gothic Bold',
	'Corbel',
	'Cordia New',
	'CordiaUPC',
	'Coronetscript',
	'DaunPenh',
	'David',
	'DengXian',
	'DFKai-SB',
	'DilleniaUPC',
	'DokChampa',
	'Dotum',
	'DotumChe',
	'Ebrima',
	'Estrangelo Edessa',
	'EucrosiaUPC',
	'Euphemia',
	'FangSong',
	'FrankRuehl',
	'FreesiaUPC',
	'Gabriola',
	'Gadugi',
	'Gautami',
	'Georgia Pro',
	'Gill Sans Nova',
	'Gisha',
	'Gulim',
	'GulimChe',
	'Gungsuh',
	'GungsuhChe',
	'Hebrew',
	'HoloLens MDL2 Assets',
	'Ink Free',
	'IrisUPC',
	'Iskoola Pota',
	'Japanese',
	'JasmineUPC',
	'Javanese Text',
	'KaiTi',
	'Kalinga',
	'Kartika',
	'Khmer UI',
	'KodchiangUPC',
	'Kokila',
	'Korean',
	'Lao',
	'Lao UI',
	'Latha',
	'Leelawadee',
	'Leelawadee UI',
	'Leelawadee UI Semilight',
	'Levenim MT',
	'LilyUPC',
	'Lucida Handwriting',
	'Lucida Sans Unicode',
	'Malgun Gothic',
	'Malgun Gothic Semilight',
	'Mangal',
	'Marlett',
	'Meiryo',
	'Meiryo UI',
	'Microsoft Himalaya',
	'Microsoft JhengHei',
	'Microsoft JhengHei UI',
	'Microsoft New Tai Lue',
	'Microsoft PhagsPa',
	'Microsoft Sans Serif',
	'Microsoft Tai Le',
	'Microsoft Uighur',
	'Microsoft YaHei',
	'Microsoft YaHei UI',
	'Microsoft Yi Baiti',
	'MingLiU',
	'MingLiU_HKSCS',
	'MingLiU_HKSCS-ExtB',
	'MingLiU-ExtB',
	'Miriam',
	'Mongolian Baiti',
	'MoolBoran',
	'MS Gothic',
	'MS Mincho',
	'MS PGothic',
	'MS PMincho',
	'MS UI Gothic',
	'MV Boli',
	'Myanmar Text',
	'Narkisim',
	'Neue Haas Grotesk Text Pro',
	'News Gothic MT',
	'Nirmala UI',
	'No automatic language associations',
	'NSimSun',
	'Nyala',
	'Palatino Linotype',
	'Plantagenet Cherokee',
	'PMingLiU',
	'Raavi',
	'Rockwell Nova',
	'Rockwell Nova Cond',
	'Rockwell Nova Extra Bold',
	'Rod',
	'Sakkal Majalla',
	'Sanskrit Text',
	'Segoe MDL2 Assets',
	'Segoe Print',
	'Segoe Script',
	'Segoe UI Emoji',
	'Segoe UI Historic',
	'Segoe UI Symbol',
	'Shonar Bangla',
	'Shruti',
	'SimHei',
	'SimKai',
	'Simplified Arabic',
	'Simplified Chinese',
	'SimSun',
	'SimSun-ExtB',
	'Sitka',
	'Sylfaen',
	'Symbol',
	'Tahoma',
	'Thai',
	'Traditional Arabic',
	'Traditional Chinese',
	'Tunga',
	'UD Digi Kyokasho',
	'UD Digi KyoKasho NK-R',
	'UD Digi KyoKasho NP-R',
	'UD Digi KyoKasho N-R',
	'Urdu Typesetting',
	'Utsaah',
	'Vani',
	'Verdana Pro',
	'Vijaya',
	'Vrinda',
	'Webdings',
	'Westminster',
	'Wingdings',
	'Yu Gothic',
	'Yu Gothic UI',
	'Yu Mincho',
];
